# -*- coding: utf-8 -*-
"""Atoms, molecules and nuclei assignment 3 question 2c.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-BXo7_POY45NyOU8MC6rMvD6HW7LQ7G
"""

import numpy as np
import matplotlib.pyplot as plt

#Exploring the radial solution to the Hydrogen atom
#The radius, r, is expressed in units of Bohr radius a0, as rho = r/a0

# define the array:
rho = np.linspace(0,10,1001)

#define the infinitesimal
drho = rho[1] - rho[0]

#define the Bohr radius:
a0=1

# Define Zeff for Sodium (Na, Z=11) using Slater's Rules
def compute_Zeff():
  Zeff_1s = 11 - (0.3*1)
  Zeff_2s = Zeff_2p = 11 - (0.85*2 + 0.35*7)
  Zeff_3s = 11 - (1*2 + 0.85*8)
  return Zeff_1s, Zeff_2s, Zeff_2p, Zeff_3s

Zeff_1s, Zeff_2s, Zeff_2p, Zeff_3s = compute_Zeff()

# Adjust rho for Zeff
rho_values = {}
for n, ell, Zeff in [(1,0, Zeff_1s), (2,0, Zeff_2s), (2,1, Zeff_2p), (3,0, Zeff_3s)]:
    rho_values[(n, ell)] = rho * Zeff

#Write the radial wavefunction:
wavefunctions = {}

for (n, ell), rho_eff in rho_values.items():
    if(n==1 and ell==0):
      psi_r = 2*np.exp(-rho_eff)/np.sqrt(a0**3)
    elif(n==2 and ell==0):
      psi_r = (1-rho_eff/2)*np.exp(-rho_eff/2)/np.sqrt(2*a0**3)
    elif(n==2 and ell==1):
      psi_r = rho_eff*np.exp(-rho_eff/2)/np.sqrt(24*a0**3)
    elif(n==3 and ell==0):
      psi_r = (1 - 2/3*rho_eff + 2/27*rho_eff**2)*np.exp(-rho_eff/3)*2/np.sqrt(27*a0**3)

    wavefunctions[(n, ell)] = psi_r
    plt.plot(rho_eff, psi_r, label=f'{n}{"s" if ell ==0 else "p"}')

plt.xlabel('$r/a_0$')
plt.ylabel('$\psi(r/a_0)$')
plt.legend()
plt.title('Radial Wavefunctions with Zeff Adjustments')
plt.show()

# Compute and plot probability densities
for (n, ell), psi_r in wavefunctions.items():
    rho_eff = rho_values[(n, ell)]
    Pr = psi_r**2 * rho_eff**2
    normalization_factor = np.trapezoid(Pr, rho_eff)
    Pr /= normalization_factor # Normalise probability distribution
    plt.plot(rho_eff, Pr, label=f'{n}{"s" if ell ==0 else "p"}')

plt.xlabel('$r/a_0$')
plt.ylabel('$P(r)dr$')
plt.legend()
plt.title('Normalised Probability Densities with Zeff Adjustments')
plt.show()

# Compute probability of electron being inside r < a0
for (n, ell), psi_r in wavefunctions.items():
    rho_eff = rho_values[(n, ell)]
    Pr = psi_r**2 * rho_eff**2
    normalization_factor = np.trapezoid(Pr, rho_eff)
    Pr /= normalization_factor # Normalise probability distribution
    mask = rho_eff < a0
    probability = np.trapezoid(Pr[mask], rho_eff[mask])
    print(f'Probability for {n}{"s" if ell == 0 else "p"} inside r < a0: {probability: .3f}')