# -*- coding: utf-8 -*-
"""Atoms, molecules and nuclei assignment 3 question 2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuddtZmx6-gn7MyxN9t34uau8Yzhgxif
"""

import numpy as np
import matplotlib.pyplot as plt

#Exploring the radial solution to the Hydrogen atom
#The radius, r, is expressed in units of Bohr radius a0, as rho = r/a0

rho = np.linspace(1, 30, 1001)

#define the infinitesimal
drho = rho[1] - rho[0]

#define the Bohr radius:
a0=1

#Write the radial wavefunction:
wavefunctions = {}

for n, ell in [(1,0), (2,0), (2,1), (3,0)]:
    if(n==1 and ell==0):
      psi_r = 2*np.exp(-rho)/np.sqrt(a0**3)
    elif(n==2 and ell==0):
      psi_r = (1-rho/2)*np.exp(-rho/2)/np.sqrt(2*a0**3)
    elif(n==2 and ell==1):
      psi_r = rho*np.exp(-rho/2)/np.sqrt(24*a0**3)
    elif(n==3 and ell==0):
      psi_r = (1 - 2/3*rho + 2/27*rho**2)*np.exp(-rho/3)*2/np.sqrt(27*a0**3)

    wavefunctions[(n, ell)] = psi_r
    plt.plot(rho, psi_r, label=f'{n}{"s" if ell ==0 else "p"}')

plt.xlabel('$r/a_0$')
plt.ylabel('$\psi(r/a_0)$')
plt.legend()
plt.title('Radial Wave Functions')
plt.show()

# Compute and plot probability densities
for (n, ell), psi_r in wavefunctions.items():
    Pr = psi_r**2 * rho**2
    normalization_factor = np.sum(Pr) * drho
    Pr /= normalization_factor # Normalise probability distribution
    plt.plot(rho, Pr, label=f'{n}{"s" if ell ==0 else "p"}')

plt.xlabel('$r/a_0$')
plt.ylabel('$P(r)dr$')
plt.legend()
plt.title('Normalised Probability Densities')
plt.show()

# Compute probability of electron being inside r < a0
for (n, ell), psi_r in wavefunctions.items():
    Pr = psi_r**2 * rho**2
    normalization_factor = np.sum(Pr) * drho
    Pr /= normalization_factor # Normalise probability distribution
    mask = rho < a0
    probability = np.sum(Pr[mask]) * drho
    print(f'Probability for {n}{"s" if ell == 0 else "p"} inside r < a0: {probability: .3f}')